# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-05 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['-create_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
    ]
