# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-05 20:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_index', '0002_auto_20181105_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='博客内容'),
        ),
    ]
