# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-05 20:20
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_index', '0003_auto_20181105_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='博客内容'),
        ),
    ]
