# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-05 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_index', '0004_auto_20181105_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blog_read',
            field=models.IntegerField(default=0),
        ),
    ]
