# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-05 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_index', '0005_blogmodel_blog_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogReadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_read', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='blog_read',
        ),
        migrations.AddField(
            model_name='blogreadmodel',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='blog_index.BlogModel'),
        ),
    ]
