# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-05 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_index', '0006_auto_20181105_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogreadmodel',
            options={'verbose_name': '阅读量', 'verbose_name_plural': '阅读量'},
        ),
        migrations.AlterField(
            model_name='blogreadmodel',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='blog_index.BlogModel', verbose_name='博客'),
        ),
        migrations.AlterField(
            model_name='blogreadmodel',
            name='blog_read',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AlterModelTable(
            name='blogreadmodel',
            table='blog_read',
        ),
    ]
