# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-05 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_index', '0007_auto_20181105_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogreadmodel',
            name='blog',
        ),
        migrations.DeleteModel(
            name='BlogReadModel',
        ),
    ]
